apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: labap.net
  namespace: demo-site
spec:
  secretName: labap.net-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - labap.net
